#!/usr/bin/env bash
# =============================================================================
# node-init.sh - Writes node-specific computed values into .env
#
# It derives values for this host from NODE_NAME (passed via $1) and appends a
# computed section to .env.
#
# Usage:
#   ./scripts/node-init.sh <node>
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."

# Initialize .env from template if missing
if [ ! -f .env ]; then
    cp .env.example .env
    echo "==> Copied .env from .env.example"
fi

# Load .env safely (no shell eval)
. "$(dirname "$0")/env-load.sh"
load_env .env

# ---------------------------------------------------------------------------
# Determine NODE_NAME
# ---------------------------------------------------------------------------
if [ $# -ge 1 ]; then
    NODE_NAME="$1"
fi

if [ -z "${CLUSTER_NODES:-}" ]; then
    echo "CLUSTER_NODES missing in .env (e.g. CLUSTER_NODES=ns1,ns2,ns3,ns4)." >&2
    exit 1
fi

case ",${CLUSTER_NODES}," in
    *,"${NODE_NAME}",*) : ;;
    *)
        echo "NODE_NAME is '$NODE_NAME' - it must be included in CLUSTER_NODES: ${CLUSTER_NODES}" >&2
        exit 1
        ;;
esac

echo "==> Configuring as $NODE_NAME"

# ---------------------------------------------------------------------------
# Indirect variable lookup: NODE_NS1_* -> NODE_*
# ---------------------------------------------------------------------------
NODE_PREFIX="$(echo "$NODE_NAME" | tr '[:lower:]' '[:upper:]')"

resolve() {
    # $1 = attr, e.g. WG_IP -> NODE_NS1_WG_IP
    local var="NODE_${NODE_PREFIX}_${1}"
    echo "${!var:-}"
}

NODE_WG_IP="$(resolve WG_IP)"
NODE_WG_AF="$(resolve WG_AF)"
NODE_PUBLIC_IPV4="$(resolve PUBLIC_IPV4)"
NODE_PUBLIC_IPV6="$(resolve PUBLIC_IPV6)"
NODE_FQDN="${NODE_NAME}.${NODE_FQDN_DOMAIN}"

NODE_SITE="$(resolve SITE)"

# Patroni policy for this node
PRIO_VAR="PATRONI_FAILOVER_PRIORITY_${NODE_PREFIX}"
NOFO_VAR="PATRONI_NOFAILOVER_${NODE_PREFIX}"
PATRONI_FAILOVER_PRIORITY="${!PRIO_VAR:-50}"
PATRONI_NOFAILOVER="${!NOFO_VAR:-false}"

if [ -z "${NODE_WG_IP:-}" ]; then
    echo "NODE_WG_IP could not be determined. Expected NODE_${NODE_PREFIX}_WG_IP in .env." >&2
    exit 1
fi
if [ -z "${NODE_WG_AF:-}" ]; then
    NODE_WG_AF="auto"
fi

# ---------------------------------------------------------------------------
# Remove existing computed section from .env and write a fresh one
# ---------------------------------------------------------------------------
# Marker
START_MARK="# >>> NODE_INIT_COMPUTED_BEGIN >>>"
END_MARK="# <<< NODE_INIT_COMPUTED_END <<<"

# Nur Original behalten (alles vor START_MARK, falls existent)
if grep -q "$START_MARK" .env; then
    sed -i "/$START_MARK/,/$END_MARK/d" .env
fi

cat >> .env <<EOF
$START_MARK
# Auto-generated by scripts/node-init.sh at $(date -Iseconds)
NODE_NAME=${NODE_NAME}
NODE_SITE=${NODE_SITE}
NODE_WG_IP=${NODE_WG_IP}
NODE_WG_AF=${NODE_WG_AF}
NODE_PUBLIC_IPV4=${NODE_PUBLIC_IPV4}
NODE_PUBLIC_IPV6=${NODE_PUBLIC_IPV6}
NODE_FQDN=${NODE_FQDN}
PATRONI_FAILOVER_PRIORITY=${PATRONI_FAILOVER_PRIORITY}
PATRONI_NOFAILOVER=${PATRONI_NOFAILOVER}
$END_MARK
EOF

echo "    NODE_WG_IP        = $NODE_WG_IP"
echo "    NODE_FQDN         = $NODE_FQDN"
echo "    Failover priority  = $PATRONI_FAILOVER_PRIORITY (nofailover=$PATRONI_NOFAILOVER)"
echo "    WG address family  = $NODE_WG_AF"
echo
echo "==> .env updated."
