# =============================================================================
# WireGuard - auto-generated by scripts/wireguard-render.sh
# =============================================================================
# Endpoints are FQDNs, NOT IPs! WireGuard resolves them when wg-quick starts;
# the reresolve timer (host systemd) re-resolves them every 5 minutes and swaps
# peer endpoints if the DNS answer has changed.
# This makes IP changes transparent - you only update the DNS record.
# =============================================================================

[Interface]
Address     = __WG_ADDRESS__/24
ListenPort  = 51820
PrivateKey  = __PRIVATE_KEY__
# Optional: if your provider MTU < 1500, 1280 is a safe choice
# MTU = 1280

# >>> PEER_BLOCKS_BEGIN >>>
# Replaced by wireguard-render.sh
# <<< PEER_BLOCKS_END <<<
